## Neural Network Introduction #2

This exercise is adapted from https://www.springboard.com/blog/beginners-guide-neural-network-in-python-scikit-learn-0-18/

Now you have successfully used SciKit Learn's MLP to work on the built-in Breast Cancer Data Set, let's try another one!

Download the wine dataset from UCI Machine learning repository (http://archive.ics.uci.edu/ml/datasets/Wine/). Import the dataset into a pandas dataframe

In [21]:
import pandas as pd

wine = pd.read_csv('Wine.csv', names = ['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline',
       'Cultivator'])

In [22]:
wine.columns

Index(['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline',
       'Cultivator'],
      dtype='object')

Check out the dataframe - what are the first few rows of data?

In [23]:
# find out the attributes in the dataset
wine.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0  Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols   
1    14.23        1.71  2.43          15.6        127            2.8   
2     13.2        1.78  2.14          11.2        100           2.65   
3    13.16        2.36  2.67          18.6        101            2.8   
4    14.37        1.95   2.5          16.8        113           3.85   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0  Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue   
1        3.06                  0.28             2.29             5.64  1.04   
2        2.76                  0.26             1.28             4.38  1.05   
3        3.24                   0.3             2.81             5.68  1.03   
4        3.49                  0.24             2.18              7.8  0.86   

   OD280  Proline        Cultivator  
0  OD280  Proline  Customer_Segment  
1   3.92     1065                 1  
2    3.4     1050                 1  
3   3.17     1185                 1  
4   3.45     1480                 1

In [60]:
wine = wine.drop([0])

In [61]:
# find out the total instances and number of features
wine.describe().transpose()

count unique    top freq
Alcohol                178    126  13.05    6
Malic_Acid             178    133   1.73    7
Ash                    178     79    2.3    7
Ash_Alcanity           178     63     20   15
Magnesium              178     53     88   13
Total_Phenols          178     97    2.2    8
Flavanoids             178    132   2.65    4
Nonflavanoid_Phenols   178     39   0.43   11
Proanthocyanins        178    101   1.35    9
Color_Intensity        178    132    3.8    4
Hue                    178     78   1.04    8
OD280                  178    122   2.87    5
Proline                178    121    520    5
Cultivator             178      3      2   71

In [62]:
# use describe to find out more about the data
wine.shape

(178, 14)

**Q:** what can you say about this dataset?

Now, set up the data (x) and labels (y)


In [63]:
x = wine.drop('Cultivator',axis=1)
y = wine['Cultivator']

#### Train Test Split
 
Let's split our data into training and testing sets, this is done easily with SciKit Learn's train_test_split function from model_selection:

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)

#### Data Preprocessing
 
The neural network may have difficulty converging before the maximum number of iterations allowed if the data is not normalized. Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data. Note that you must apply the same scaling to the test set for meaningful results. There are a lot of different methods for normalization of data, we will use the built-in StandardScaler for standardization.

In [65]:
# Import the StandardScalar library
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit only to the training data
scaler.fit(x_train)
StandardScaler(copy = True, with_mean = True, with_std = True)

StandardScaler()

In [66]:
# Now apply the transformations to the data:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

#### Training the model
 
Now it is time to train our model. SciKit Learn makes this incredibly easy, rby using estimator objects. In this case we will import our estimator (the Multi-Layer Perceptron Classifier model) from the neural_network library of SciKit-Learn!

In [67]:
from sklearn.neural_network import MLPClassifier

Next we create an instance of the model, there are a lot of parameters you can choose to define and customize here, we will only define the hidden_layer_sizes. For this parameter you pass in a tuple consisting of the number of neurons you want at each layer, where the nth entry in the tuple represents the number of neurons in the nth layer of the MLP model. There are many ways to choose these numbers, but for simplicity we will choose 3 layers with the same number of neurons as there are features in our data set:

In [68]:
# create a Multilayerperceptron classifier and call it mlp
mlp =   MLPClassifier(hidden_layer_sizes = (13,13,13))

Now that the model has been made we can fit the training data to our model, remember that this data has already been processed and scaled:

In [69]:
mlp.fit(x_train, y_train)

C:\Users\User\anaconda3\envs\python-dscourse\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(13, 13, 13))

**Q:** What do you see in the output? What does it tell you?

#### Predictions and Evaluation
 
Now that we have a model it is time to use it to get predictions! We can do this simply with the predict() method off of our fitted model:

In [70]:
predictions = mlp.predict(x_test)

Now we can use SciKit-Learn's built in metrics such as a classification report and confusion matrix to evaluate how well our model performed:

In [73]:
from sklearn.metrics import classification_report, confusion_matrix

print (confusion_matrix(y_test, predictions))

[[11  0  0]
 [ 2 25  0]
 [ 0  0  7]]


**Q:** what conclusion can you make from the confusion matrix?

#### Weights and biases

The downside however to using a Multi-Layer Preceptron model is how difficult it is to interpret the model itself. The weights and biases won't be easily interpretable in relation to which features are important to the model itself.

To extract the MLP weights and biases after training your model, you use its public attributes coefs_ and intercepts_.

In [74]:
# Print the coefficient values and interpret it
len (mlp.coefs_[0])

13

In [75]:
# Print the intercepts values and interpret it
len (mlp.intercepts_[0])

13

**Q:** What do you understand from the two values?

#### Additional optional tasks...

select a few known supervised techniques and compare their performance. Use 10 fold cross validation

In [77]:
from numpy import mean
from numpy import std
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

cv = RepeatedKFold(n_splits = 10, n_repeats = 3, random_state = 1)

model = LogisticRegression()
scores = cross_val_score(model, x, y, scoring = 'accuracy', cv = cv, n_jobs = -1)

print ('Accuracy:%.3f (%.3F)'%(mean(scores), std(scores)))

Accuracy:0.949 (0.049)
